### PR TITLE
Force deployments to use composer v1 and don't yarn validate

### PR DESCRIPTION
**Pull request by msawicki**
## What does this do/fix?

This should get deploys running again, forcing use of composer v1 and skipping `yarn validate` for now.

### CODE REVIEW

**Review by jbrinley — APPROVED** [review]
Can we just delete `yarn validate` instead of commenting it?

**Review by nickpelton — APPROVED** [review]
👍

If yarn validate is failing should we have the UI team fix that?

**Comment by dpellenwood** [comment]
I can fix the linter issues here on this branch. Please hold...

**Comment by dpellenwood** [comment]
@msawicki `yarn validate` should no longer fail on deploys.

**Pull request merged**
