### PR TITLE
Updates fields to use field section accordions

### PR DESCRIPTION
**Pull request by msawicki**
## What does this do/fix?

Per the conversation this week, this change used the tribe-libs new Field_Section to create content sections inside the plugin and out of tribe libs. This is specifically using accordions for the sections. This is dependent on the changes in https://github.com/moderntribe/tribe-libs/pull/69

### CODE REVIEW

**Review by ryanurban — COMMENTED** [review]
Thanks for hitting this too, Mike! In this shift I'm not sure we need even a formal `Field_Section` abstraction either. It's one less thing we'd need to translate from design via gui acf declarations just using the accordion field. Thoughts?

**Comment by msawicki** [comment]
Note the tests are failing because of the missing dependency in tribe libs.

**Comment by msawicki** [comment]
@ryanurban I feel pretty strongly about having the separation here for sections. It's a nice visual and structural breakup of the section definition and personally think it improves the overall readability and ability to see what's going on. It is, however, optional. I dev could just use ->add_field() for a section with the ACF config array.

**Comment by ryanurban** [comment]
Fair enough and true

**Review by dpellenwood — APPROVED** [review]
Looks great. Thank you for tackling this.

**Review by jbrinley — APPROVED** [review]
I like this API much better.

**Comment by dpellenwood** [comment]
@msawicki is there anything holding this up from merging?

**Pull request merged**
