### PR TITLE
Allow us to set `opcache.validate_timestamps=0` in php.ini

### PR DESCRIPTION
**Pull request by defunctl**
Just did this for LL in https://github.com/moderntribe/little-league/pull/428

I think it should be the standard config in the upcoming Template refactor.

### CODE REVIEW

**Comment by jbrinley** [comment]
I _think_ this makes sense, but can you provide a little more context about what this is accomplishing, and why it should be the default?

**Comment by defunctl** [comment]
> I _think_ this makes sense, but can you provide a little more context about what this is accomplishing, and why it should be the default?

Absolutely. On production environments (where we have this control), we should really be disabling opcache timestamp validation: https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.validate-timestamps.

While someone may remember to configure this in php.ini, it would cause all kinds of unintended caching with Twig, just enabling this option could save a number of headaches down the road.

Given Tribe Cache also calls `opcache_reset()` this would properly flush the Twig cache with no timestamp validation enabled.

More reading: https://twig.symfony.com/doc/2.x/recipes.html#refreshing-modified-templates-when-opcache-or-apc-is-enabled

**Comment by jbrinley** [comment]
Are there any negative side effects if we have this value set on a server that does _not_ use `opcache.validate_timestamps=0`?

**Comment by defunctl** [comment]
> Are there any negative side effects if we have this value set on a server that does _not_ use `opcache.validate_timestamps=0`?

Very good question, and I don't now that answer 100%. It basically asks Twig to invalidate the opache when writing a file with error suppression: https://github.com/twigphp/Twig/blob/3.x/src/Cache/FilesystemCache.php#L64

**Comment by jbrinley** [comment]
Seems safe. 🤷‍♂

**Comment by defunctl** [comment]
Let me know if you run into any issues.

**Pull request merged**
