### PR TITLE
[SQONE-710] Bugfixes from Smoketest

### PR DESCRIPTION
**Pull request by LayaTaal**
## What does this do/fix?

This PR addresses a number of minor bugs found during recent smoketesting. Details around those fixes can be found in the [spreadsheet here](https://docs.google.com/spreadsheets/d/1NA_XOkKS_Iq1tzWnekc2SuV2XgJLtJWxB6rJsZxdOCM/edit#gid=0).

## QA

Links to relevant issues
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-710)

Links to deployed, scaffolded demo:
- [Link to Demo](https://sq1-pr1034.moderntribe.qa/smoketest-fix-demos/?secret=1)

## Screenshots/video
**ACF Gallery Field Updates**
- Before: http://p.tri.be/3STntT
- After: http://p.tri.be/LAC2yy

**Links Block**
image

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because...
- [ ] No, I need help figuring out how to write the tests.

### CODE REVIEW

**Review by Vinsanity — APPROVED** [review]
LGTM Jason. Thanks for tackling these. The gallery one makes sense, considering the restrictions in the inspector panel for blocks. The link block I'm not all that familiar with so the issues with the Link_Header I'll defer to others for confirmation.

**Comment by LayaTaal** [comment]
> LGTM Jason. Thanks for tackling these. The gallery one makes sense, considering the restrictions in the inspector panel for blocks. The link block I'm not all that familiar with so the issues with the Link_Header I'll defer to others for confirmation.

@Vinsanity just to clarify the removal of `Link_Header` is because there is no mention of it in the designs, so it wasn't quite clear to @dpellenwood and I why it was included. If someone else has more insight on this, I can definitely add it back in.

**Review by dpellenwood — APPROVED** [review]
This is great Jason! Thanks for tackling these!

**Review by jamiepaul — APPROVED** [review]
👍 👍 👍  looks great, Jason!

**Pull request merged**
