### PR TITLE
[SQONE-692] P2P Integration Fix

### PR DESCRIPTION
**Pull request by clontztopher**
## What does this do/fix?

- Corrects missing post titles in the P2P metabox
- Corrects the P2P ID argument type when caching P2P connections.

## QA

Links to relevant issues
- [SQONE-692](https://moderntribe.atlassian.net/browse/SQONE-692)

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because...
- [ ] No, I need help figuring out how to write the tests.

### CODE REVIEW

**Comment by defunctl** [comment]
Hey @clontztopher,

If there's a bug related to p2p we should be fixing it in Tribe Libs, as it's already using these filters and also older projects will be able to get the fix.

https://github.com/moderntribe/tribe-libs/tree/master/src/P2P

If you need any help/guidance feel free to ping me on slack.

**Comment by dpellenwood** [comment]
> If there's a bug related to p2p we should be fixing it in Tribe Libs, as it's already using these filters and also older projects will be able to get the fix.

Ah, interesting. I didn't know we are already filtering P2P in Tribe Libs. @clontztopher , please pull out the filter work here and just leave [the parameter type fix](https://github.com/moderntribe/square-one/pull/956/files#diff-c180f47591fad3d3ae76415966e03ef9f4287c97796a72ab6f74f0558d6a9b37). We'll address the filters in Tribe Libs as Justin mentions.

Thank you both!

**Comment by clontztopher** [comment]
@dpellenwood @defunctl Sure thing 👍

**Comment by clontztopher** [comment]
@dpellenwood Updates pushed

**Review by dpellenwood — APPROVED** [review]
:shipit:

**Pull request merged**
