### PR TITLE
Proper wp_nav_menu() $args type

### PR DESCRIPTION
**Pull request by defunctl**
## What does this do/fix?

Getting ahead of another casting issue we ran into on another project.

WordPress claims the $args are an array, but they cast it as an object in a function.

## QA

- Menus on the frontend will no longer throw an error once types are added. 

## Tests

Does this have tests?

- [ ] Yes
- [x] No
- [ ] No, I need help figuring out how to write the tests.

### CODE REVIEW

**Review by nickpelton — APPROVED** [review]
Interesting it was failing since $arg was casted in the method. No objections to moving it. Approved.

**Comment by defunctl** [comment]
> Interesting it was failing since $arg was casted in the method. No objections to moving it. Approved.

It's not casted in the method, the expectation is defined in the method.

Actually, I think they fixed this and we're now just passing the [wrong type](https://github.com/WordPress/WordPress/blob/5.7-branch/wp-includes/class-walker-nav-menu.php#L199)

**Comment by defunctl** [comment]
@nickpelton updated this to properly match WordPress now.

**Comment by nickpelton** [comment]
I meant how it was casting it inside the method just like you did on the subscriber. `$args = (array) $args;`. But yeah, they look to have fixed it.

**Review by nickpelton — APPROVED** [review]

**Pull request merged**
