### PR TITLE
Update ACF,TEC, Yoast, Gravity forms and Tribe Libs (to 3.4.12) and WP to 5.9.2

### PR DESCRIPTION
**Pull request by defunctl**
## What does this do/fix?

- Title says it all.

## QA

@dpellenwood I wonder if ya'll can easily test this is working https://github.com/moderntribe/tribe-libs/pull/111 ?

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because it's just dependency updates.
- [ ] No, I need help figuring out how to write the tests.

### CODE REVIEW

**Review by dpellenwood — COMMENTED** [review]
Thanks for tackling this, @defunctl. I tested out the P2P fixes from Tribe Libs and found they didn't work. [Created a new PR](https://github.com/moderntribe/tribe-libs/pull/112) to properly address that and another bug I found along the way.

Additionally, wondering if we want to go ahead and update WP Core to 5.9.2 and ACF to the latest version (5.12.1) with this PR as well? We've been using v5.9.x during dev for Harvard Public Health and haven't come cross any blocking issues.

**Comment by defunctl** [comment]
> Thanks for tackling this, @defunctl. I tested out the P2P fixes from Tribe Libs and found they didn't work. [Created a new PR](https://github.com/moderntribe/tribe-libs/pull/112) to properly address that and another bug I found along the way.
> 
> Additionally, wondering if we want to go ahead and update WP Core to 5.9.2 and ACF to the latest version (5.12.1) with this PR as well? We've been using v5.9.x during dev for Harvard Public Health and haven't come cross any blocking issues.

@dpellenwood updated

**Comment by defunctl** [comment]
I need a new database export to get the tests to pass, hold tight.

**Review by dpellenwood — APPROVED** [review]
Thanks Justin!

**Pull request merged**
