### PR TITLE
Feature/sqone 429/lefthook git hooks

### PR DESCRIPTION
**Pull request by defunctl**
## What does this do/fix?

- Replaces husky hooks with https://github.com/evilmartians/lefthook to run git-hooks. I couldn't get a number of things working properly and this executes much faster and is much more configurable. See https://github.com/evilmartians/lefthook/blob/master/docs/full_guide.md for configuration options.
- Commits will be prefixed with the Jira ticket for better historical tracking purposes in projects. Example with this branch: `[SQONE-429] my original commit message`

## QA

- yarn install should activate the hooks automatically, if not you can run `lefthook install` or `lefthook install -a` to remove all existing hooks and replace with these ones.
- phpcs should run only on changed files in the core plugin/theme and the mu-plugins folder.
- branches without a Jira ticket should just commit as normal without adding the ticket prefix.

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because it changes how git-hooks are configured.
- [ ] No, I need help figuring out how to write the tests.

[SQONE-429]: https://moderntribe.atlassian.net/browse/SQONE-429

### CODE REVIEW

**Comment by nickpelton** [comment]
Worked but does not properly remove the husky git hook. Please add docs somewhere on how to clean up after the switch.

``` 
nick@NickMBP2018  squareOneEdit   feature/SQONE-429/lefthook-git-hooks  git commit --allow-empty -m "test lefthooks"     

SUMMARY: (SKIP EMPTY)

SUMMARY: (done in 0.04 seconds)
✔️  prefix_with_jira_ticket
Can't find Husky, skipping commit-msg hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
Can't find Husky, skipping post-commit hook
You can reinstall it using 'npm install husky --save-dev' or delete this hook
[feature/SQONE-429/lefthook-git-hooks d1562162b] [SQONE-429] test lefthooks
```

**Comment by defunctl** [comment]
> Worked but does not properly remove the husky git hook. Please add docs somewhere on how to clean up after the switch.
> 
> ```
> nick@NickMBP2018  squareOneEdit   feature/SQONE-429/lefthook-git-hooks  git commit --allow-empty -m "test lefthooks"     
> 
> SUMMARY: (SKIP EMPTY)
> 
> SUMMARY: (done in 0.04 seconds)
> ✔️  prefix_with_jira_ticket
> Can't find Husky, skipping commit-msg hook
> You can reinstall it using 'npm install husky --save-dev' or delete this hook
> Can't find Husky, skipping post-commit hook
> You can reinstall it using 'npm install husky --save-dev' or delete this hook
> [feature/SQONE-429/lefthook-git-hooks d1562162b] [SQONE-429] test lefthooks
> ```

Run `lefthook install -a`. I'll look for a place to add docs

**Comment by defunctl** [comment]
@nickpelton docs added

**Review by nickpelton — APPROVED** [review]
Worked like a charm. 🚀

**Pull request merged**
