### PR TITLE
Can't make this a required check with paths

### PR DESCRIPTION
**Pull request by defunctl**
## What does this do/fix?

If you make the eslint action part of `Require status checks to pass before merging` for a branch and no files are changed, it never runs and therefore never completes and sits waiting forever. The only solution I could come up with is to make it run, as it already filters which files it runs on.

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because it's a GitHub action.
- [ ] No, I need help figuring out how to write the tests.

### CODE REVIEW

**Review by nickpelton — APPROVED** [review]
Approved. Should we also make this run on push to main so we check post merge?

**Comment by defunctl** [comment]
> Approved. Should we also make this run on push to main so we check post merge?

Great idea, I'll update it.

**Review by nickpelton — APPROVED** [review]
🚀

**Review by dpellenwood — APPROVED** [review]
Nice catch, Justin.

**Comment by nickpelton** [comment]
Hey @defunctl ready to merge.

**Pull request merged**
