### PR TITLE
Updating the eslint file to include JS in the component directory

### PR DESCRIPTION
**Pull request by ScottGarrison**
## What does this do/fix?

- Adds in the component JS files to our eslint command
- Ran it for testing and it includes the dialog JS file updates.

### CODE REVIEW

**Review by nickpelton — APPROVED** [review]
Looks good. I'm surprised the theme check with `**/*` doesn't pick up the component folders. I thought `**/*` was essentially recursive folder checks. 🤷

**Comment by ScottGarrison** [comment]
Only within the root structure. None of our checks currently had the root outside of the JS folder

**Comment by nickpelton** [comment]
Do we have the same issue with the stylelint? It also is scoped to only look directly into the `wp-content/themes/core/assets/css/src/theme/` folder. So it wouldn't be checking the components properly either, correct? Can we fix that as part of this PR as well?

**Comment by dpellenwood** [comment]
> Do we have the same issue with the stylelint? ... Can we fix that as part of this PR as well?
Agreed. Let's add the components path to stylelint as well.

I'd suggest we should add the integrations folder path to both eslint and stylelint as well.

**Review by dpellenwood — CHANGES_REQUESTED** [review]
Changes look great. Please add integrations to eslint and component & integrations paths to the theme stylelint task.

**Comment by ScottGarrison** [comment]
@nickpelton @dpellenwood I made the requested changes but the Codeception test is failing. Seems like it's running tests or lint on files that don't exist, and I cant even find the variables it's calling out in our file structure. Must be something running i'm not familiar with

**Comment by ScottGarrison** [comment]
@nickpelton @dpellenwood This is good for a recheck with the added lint for the component css and integrations

**Review by dpellenwood — APPROVED** [review]
Awesome! Thank you Scott!

**Pull request merged**
