### PR TITLE
Updates linting to include JS and CSS files.

### PR DESCRIPTION
**Pull request by mmcachran**

### CODE REVIEW

**Comment by ryanurban** [comment]
@mmcachran is this for the PR linting or the existing build system?

**Comment by mmcachran** [comment]
> @mmcachran is this for the PR linting or the existing build system?

This is for any staged files getting committed to the repo. PHP linting is already in place, this just adds it for JS and CSS.

**Comment by ryanurban** [comment]
Ah ok cool. Only reason I ask is we already have eslint & stylelint also setup for the theme itself and our build system, so wanted to make sure we weren't duplicating and doubling up 👍 Thanks for doing this ⚡

**Comment by jamiepaul** [comment]
@mmcachran does this work w/ the husky linting messages pre-commit? To @ryanurban's point, just want to make sure we're not doubling up.

**Comment by mmcachran** [comment]
> @mmcachran does this work w/ the husky linting messages pre-commit? To @ryanurban's point, just want to make sure we're not doubling up.

Yes, this is for pre-commit linting with Husky.

**Comment by ryanurban** [comment]
Hmm, makes me wonder if this is duplicative then, though I do like the fact that it's automated. Would you be able to leverage our existing `gulp lint` task @mmcachran and hook it up to be run as part of this instead?

**Pull request closed without merging**
